

export default function Disclaimer() {
  return (
    <div className="max-w-4xl mx-auto p-4 space-y-8 pb-20">
      <div>
        <h1 className="text-3xl font-bold tracking-tight mb-2">Impressum & Disclaimer</h1>
        <p className="text-muted-foreground">Legal information and disclaimers regarding the use of Publikater.</p>
      </div>

      <div className="space-y-6 text-sm text-foreground/80 leading-relaxed">
        <section className="bg-card p-6 rounded-lg border shadow-sm">
          <h2 className="text-xl font-semibold mb-3 text-foreground">Copyright Information</h2>
          <p>
            © {new Date().getFullYear()} Publikater AI Research Feed. All rights reserved. 
            Publikater is a personalized research feed application. The software and its native components are provided "as is".
          </p>
        </section>

        <section className="bg-card p-6 rounded-lg border shadow-sm">
          <h2 className="text-xl font-semibold mb-3 text-foreground">Content Disclaimer</h2>
          <p className="mb-4">
            Publikater aggregates academic papers, preprints, and research articles from third-party sources (primarily Semantic Scholar). 
            We do not claim ownership of the papers, abstracts, or metadata retrieved by the system.
          </p>
          <ul className="list-disc pl-5 space-y-2">
            <li><strong>AI-Generated Summaries:</strong> The Tier 2 (Gemini) and Tier 3 (Anthropic) summaries are generated by artificial intelligence. While they aim to be accurate representations of the abstract or full text, they may contain hallucinations, errors, or oversimplifications. Always read the original article to verify scientific claims.</li>
            <li><strong>External Links:</strong> This application contains links to external websites (such as bioRxiv, arXiv, and publisher sites). We are not responsible for the content, privacy policies, or practices of these third-party websites.</li>
          </ul>
        </section>

        <section className="bg-card p-6 rounded-lg border shadow-sm">
          <h2 className="text-xl font-semibold mb-3 text-foreground">Data Privacy & API Usage</h2>
          <p className="mb-4">
            Publikater runs locally. Your data, including followed topics, authors, and read history, is stored entirely on your local machine in an SQLite database.
          </p>
          <p>
            When utilizing Tier 2 or Tier 3 AI summaries, text from the papers is sent to third-party API providers (Google or Anthropic) in accordance with the API keys you provide. Please review the respective privacy policies of these providers if you have concerns about data transmission.
          </p>
        </section>
        
        <section className="bg-card p-6 rounded-lg border shadow-sm">
          <h2 className="text-xl font-semibold mb-3 text-foreground">No Medical or Professional Advice</h2>
          <p>
            The research papers and AI-generated summaries provided in this application are for informational and educational purposes only. They do not constitute medical, legal, or professional advice. Always consult a qualified professional for specific advice related to your situation.
          </p>
        </section>
      </div>
    </div>
  )
}
