"""Add is_acknowledged

Revision ID: 93d34b18c5b0
Revises: a9816306f183
Create Date: 2026-06-03 17:06:29.965655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93d34b18c5b0'
down_revision: Union[str, Sequence[str], None] = 'a9816306f183'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('is_acknowledged', sa.Boolean(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'is_acknowledged')
    # ### end Alembic commands ###
