"""Initial Item schema

Revision ID: 9fe2d79dee52
Revises: 
Create Date: 2026-06-03 16:16:09.403335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fe2d79dee52'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_native_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('authors', sa.JSON(), nullable=False),
    sa.Column('abstract', sa.String(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('doi', sa.String(), nullable=True),
    sa.Column('venue', sa.String(), nullable=True),
    sa.Column('citation_count', sa.Integer(), nullable=True),
    sa.Column('raw_metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_doi'), 'items', ['doi'], unique=False)
    op.create_index(op.f('ix_items_published_at'), 'items', ['published_at'], unique=False)
    op.create_index(op.f('ix_items_source'), 'items', ['source'], unique=False)
    op.create_index(op.f('ix_items_source_native_id'), 'items', ['source_native_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_source_native_id'), table_name='items')
    op.drop_index(op.f('ix_items_source'), table_name='items')
    op.drop_index(op.f('ix_items_published_at'), table_name='items')
    op.drop_index(op.f('ix_items_doi'), table_name='items')
    op.drop_table('items')
    # ### end Alembic commands ###
