"""Add AppConfig and Summaries

Revision ID: a9816306f183
Revises: 9a9535bc33e9
Create Date: 2026-06-03 16:55:34.008235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9816306f183'
down_revision: Union[str, Sequence[str], None] = '9a9535bc33e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_config',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('budget_tracker',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('month', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('total_cost_usd', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budget_tracker_month'), 'budget_tracker', ['month'], unique=False)
    op.add_column('items', sa.Column('t2_summary', sa.String(), nullable=True))
    op.add_column('items', sa.Column('t3_summary', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 't3_summary')
    op.drop_column('items', 't2_summary')
    op.drop_index(op.f('ix_budget_tracker_month'), table_name='budget_tracker')
    op.drop_table('budget_tracker')
    op.drop_table('app_config')
    # ### end Alembic commands ###
