"""add_tools_column

Revision ID: d1e8d65277ec
Revises: 74b89c9bb130
Create Date: 2026-06-04 11:05:34.728817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1e8d65277ec'
down_revision: Union[str, Sequence[str], None] = '74b89c9bb130'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('tools', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'tools')
    # ### end Alembic commands ###
