"""Add follow and is_starred

Revision ID: dc0c3426cecf
Revises: 93d34b18c5b0
Create Date: 2026-06-03 17:32:44.389472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc0c3426cecf'
down_revision: Union[str, Sequence[str], None] = '93d34b18c5b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follows',
    sa.Column('id', sa.String(), nullable=False, server_default='0'),
    sa.Column('entity_type', sa.String(), nullable=False, server_default='0'),
    sa.Column('entity_value', sa.String(), nullable=False, server_default='0'),
    sa.Column('boost_value', sa.Float(), nullable=False, server_default='0'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('items', sa.Column('is_starred', sa.Boolean(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'is_starred')
    op.drop_table('follows')
    # ### end Alembic commands ###
