"""add display_name to follows

Revision ID: e1b577ae9509
Revises: d1e8d65277ec
Create Date: 2026-06-07 21:21:59.388239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1b577ae9509'
down_revision: Union[str, Sequence[str], None] = 'd1e8d65277ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('follows', sa.Column('display_name', sa.String(), nullable=True))
    op.add_column('items', sa.Column('author_details', sa.JSON(), nullable=True))
    op.add_column('items', sa.Column('corpus_id', sa.String(), nullable=True))
    op.add_column('items', sa.Column('pmid', sa.String(), nullable=True))
    op.add_column('items', sa.Column('orcid_list', sa.JSON(), nullable=True))
    op.add_column('items', sa.Column('is_open_access', sa.Boolean(), nullable=False))
    op.add_column('items', sa.Column('open_access_pdf_url', sa.String(), nullable=True))
    op.add_column('items', sa.Column('reference_count', sa.Integer(), nullable=True))
    op.add_column('items', sa.Column('influential_citation_count', sa.Integer(), nullable=True))
    op.add_column('items', sa.Column('citation_styles', sa.JSON(), nullable=True))
    op.add_column('items', sa.Column('embedding', sa.JSON(), nullable=True))
    op.add_column('items', sa.Column('t1_tldr', sa.String(), nullable=True))
    op.add_column('items', sa.Column('is_hidden', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_items_corpus_id'), 'items', ['corpus_id'], unique=True)
    op.create_index(op.f('ix_items_is_acknowledged'), 'items', ['is_acknowledged'], unique=False)
    op.create_index(op.f('ix_items_is_starred'), 'items', ['is_starred'], unique=False)
    op.add_column('topics', sa.Column('keywords', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topics', 'keywords')
    op.drop_index(op.f('ix_items_is_starred'), table_name='items')
    op.drop_index(op.f('ix_items_is_acknowledged'), table_name='items')
    op.drop_index(op.f('ix_items_corpus_id'), table_name='items')
    op.drop_column('items', 'is_hidden')
    op.drop_column('items', 't1_tldr')
    op.drop_column('items', 'embedding')
    op.drop_column('items', 'citation_styles')
    op.drop_column('items', 'influential_citation_count')
    op.drop_column('items', 'reference_count')
    op.drop_column('items', 'open_access_pdf_url')
    op.drop_column('items', 'is_open_access')
    op.drop_column('items', 'orcid_list')
    op.drop_column('items', 'pmid')
    op.drop_column('items', 'corpus_id')
    op.drop_column('items', 'author_details')
    op.drop_column('follows', 'display_name')
    # ### end Alembic commands ###
